### PR TITLE
source input stream is duplicable should be judged by its own capability

### PR DESCRIPTION
**Pull request by sudison**
It's lated to the issue I opened at https://github.com/oracle/bmcs-java-sdk/issues/11. 
Not sure it's the best solution, but it does solve my current problem.

### CODE REVIEW

**Comment by sudison** [comment]
If the source stream is DuplicatableInputStream, it doesn't necessarily mean the stream can be read in parallel, right?
sounds like we need to add another method on DuplicatableInputStream, such as "boolean supportsParallelReads()".

**Comment by priteshkp** [comment]
No, they're separate concepts.  If you don't want parallel reads, you just don't configure it when uploading.  If you want parallel, it can only be done with a DuplicableInputStream.  Duplicatable is only intended to expose streams that can be safely copied (so you can consume a source stream multiple times without having to figure out mark/reset or buffering).

**Comment by priteshkp** [comment]
Tnx -- looks good to me.  @mricken can you bump the SDK to the next snapshot version before we approve/rebase/accept it?

**Comment by mricken** [comment]
Edison, one of the unit tests is failing when I try to build your changes. Did I do something wrong when I checked out your code? Can you please re-check?

Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE! - in com.oracle.bmc.objectstorage.transfer.internal.StreamChunkCreatorTest
serialChunks_readOutOfOrder(com.oracle.bmc.objectstorage.transfer.internal.StreamChunkCreatorTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[aaaaabbbbbcccccdddddeeeeef]> but was:<[dddddbbbbbfeeeeeaaaaaccccc]>
	at com.oracle.bmc.objectstorage.transfer.internal.StreamChunkCreatorTest.serialChunks_readOutOfOrder(StreamChunkCreatorTest.java:75)

**Comment by priteshkp** [comment]
Thanks for finding that, @mricken.  Edison, I believe the fix is to update the unit tests to:

1) update the existing test to use a non-DuplicatableInputStream as the source (which should make the test pass again
2) add a new unit test just like the failing one that uses the DuplicatableInputStream and verifies that bytes are read in teh order the chunks are read.

**Comment by mricken** [comment]
I have fixed the unit tests and made some other small changes. I'm not making this change here, though. Instead, it's included in our next release push to GitHub.

**Pull request closed without merging**
